[workspace]

# TODO extract simple-wrapper crates to their own repo
members = [
    "cosmic-applet-host",
    "cosmic-applet-host-config"
]

[patch.crates-io]
xkbcommon = { git = "https://github.com/rust-x-bindings/xkbcommon-rs", rev = "4e491bee" }

